name: photolocal
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio:
  cached_network_image:
  photo_view:
  path_provider:
  url_launcher:
  sembast:
  location:
  sliding_up_panel:
  shimmer:
  http:
  encrypt:
  crypto:
  flutter_spinkit:
  flutter_svg:
  permission_handler:
  auto_size_text:
  provider:
  stacked:
  i18n_extension:
  cupertino_back_gesture:
  eva_icons_flutter:
  page_transition:
  line_icons:
  flutter_staggered_animations:
  google_fonts:
  mapbox_gl:
    git:
      url: git://github.com/daniilsv/flutter-mapbox-gl.git
      ref: 04208b74e56aa085bd8904c2dce83b6669e040d9


dev_dependencies:
  build:
  build_config:
  built_value_generator:
  flutter_launcher_icons:
  json_serializable:
  build_runner:


flutter:
  uses-material-design: true
  
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf-reg.ttf
          weight: 400
        - asset: assets/fonts/sf-med.ttf
          weight: 500
        - asset: assets/fonts/sf-bol.ttf
          weight: 700
    
    - family: DrukTextWideCyTT
      fonts:
        - asset: assets/fonts/druk-reg.ttf
          weight: 400
          
    - family: NewYorkRegularItalic
      fonts:
        - asset: assets/fonts/ny-reg-it.otf
          weight: 400
          
    - family:  PhotoLocal
      fonts:
        - asset: fonts/PhotoLocal.ttf
  assets:
    # Images
    - assets/images/logo.svg
    - assets/images/account_type.jpeg
    - assets/images/entry_chooser.jpeg

    - assets/images/map/user1_chosen.png
    - assets/images/map/user1.png
    - assets/images/map/user2_chosen.png
    - assets/images/map/user2.png
    - assets/images/map/user3_chosen.png
    - assets/images/map/user3.png
    - assets/images/map/user4_chosen.png
    - assets/images/map/user4.png
    - assets/images/map/user5_chosen.png
    - assets/images/map/user5.png
    - assets/images/map/user6_chosen.png
    - assets/images/map/user6.png
    - assets/images/map/user7_chosen.png
    - assets/images/map/user7.png
    - assets/images/map/user8_chosen.png
    - assets/images/map/user8.png
    - assets/images/map/user9_chosen.png
    - assets/images/map/user9.png
    - assets/images/map/user10_chosen.png
    - assets/images/map/user10.png
    # Icons

    - assets/icons/bookmark-plus-outline.svg
    - assets/icons/safe_contract.svg

flutter_icons:
  image_path_ios: icon/full_icon.png
  image_path_android: icon/full_icon.png
  adaptive_icon_background: icon/background.png
  adaptive_icon_foreground: icon/full_icon.png
  android: true
  ios: true